services:
  - type: web
    name: image-proxy-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python proxy.py
    envVars:
      - key: PORT
        value: 10000